name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt -q install dosbox genisoimage
    - name: make
      run: |
        make
        mkdir -p artifacts
        cp win9x_essentials.iso artifacts/
    - name: Upload ISO
      uses: actions/upload-artifact@v1
      with:
        path: "artifacts"
        name: win9x_essentials_iso
