name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -q install dosbox genisoimage
    - name: make
      timeout-minutes: 20
      run: |
        make
        mkdir -p artifacts
        cp win9x_essentials.iso artifacts/
    - name: Find Git version
      id: version
      run: |
        if git describe --exact-match --tags >/dev/null; then
          VERSION=$(git describe --exact-match --tags)
          VERSION=${VERSION/#win9x-essentials-/}
        else
          VERSION=$(git rev-parse --short HEAD)
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Upload ISO
      uses: actions/upload-artifact@v1
      with:
        path: "artifacts"
        name: win9x_essentials_iso-${{steps.version.outputs.VERSION}}
